<?php


class Disc extends Wheel
{

    public $material;


    public function __construct( $brand, $seller, $price,$amount, $size,$radius,$material)
    {
        parent::__construct( $brand, $seller, $price,$amount,$size,$radius);

        $this->material=$material;

    }

    public function getSum()
    {
        // TODO: Implement getSum() method.
    }

    public  function getInfo()
    {
        return parent::getInfo()."Material: $this->material<hr>"; // TODO: Change the autogenerated stub
    }

}