<?php


class Disc extends Product
{
    private $radius;
    private $material;

    public function __construct( $brand, $seller, $price,$amount, $radius, $material)
    {
        parent::__construct( $brand, $seller, $price,$amount);
        $this->radius=$radius;
        $this->material=$material;
    }

    public  function getInfo()
    {
        return parent::getInfo()."Radius: $this->radius</br>"."Material: $this->material<hr>"; // TODO: Change the autogenerated stub
    }

}