<?php


class Tire extends Wheel
{   private $type="";


    public function __construct($brand, $seller, $price,$amount, $size,$radius,$type)
    {
        parent::__construct( $brand, $seller, $price,$amount,$size,$radius);
        $this->type=$type;

    }

    public function getSum( )
    {
      // TODO: Implement getSum() method.
    }

    public function getInfo()
    {
        return parent::getInfo()."Type: $this->type<hr>"; // TODO: Change the autogenerated stub
    }


}