<?php


class Tire extends Product
{
    private $size;
    private $diametr;

    public function __construct($brand, $seller, $price,$amount, $size,$diametr)
    {
        parent::__construct( $brand, $seller, $price,$amount);
        $this->size=$size;
        $this->diametr=$diametr;
    }

    public function getInfo()
    {
        return parent::getInfo()."Diametr: $this->diametr</br>"."Size: $this->size<hr>"; // TODO: Change the autogenerated stub
    }


}